### ISSUE TITLE
여러 음악 플랫폼의 기능과 데이터 조사 후, 각자 기능을 담당함

### ISSUE THREAD

**Issue by iamyanghee** [Melon-Shake/API#1]
### 계획했던 것
- ~오전: 데이터랑 서비스 확정~
- ~오후: 파이프라인 확정~

### 진행된 것
- 오전: 주요 서비스 api 조사 후, 종합 토의 (점심시간 이후, 14:30 정도까지 진행함)
- 오후: 우리 서비스의 주요 기능 기획 후, 각자 담당함 (16:00까지 진행함)

## 내일(8/22,화) 일정
- 09:20 | 공통개발환경 얘기하기
- 15:00  | 각자 담당한 기능을 기반으로, DB 설계 시작
- 목표 산출 |  DB

-------
## 기능 기획 회의안
[https://web.goodnotes.com/s/cBN1CTTiCn7EkYLMiRjHzR#page-5](https://web.goodnotes.com/s/cBN1CTTiCn7EkYLMiRjHzR#page-5)

**Comment by iamyanghee** [comment]
### 우리가 사용할 수 있는 음악 스트리밍 서비스 API

- 유튜브 API
  - 유튜브 뮤직만 별도의 api 가 있지 않음
- Spotify API
- Itunes API
- Shazam API

**Comment by iamyanghee** [comment]
### Spotify

**Comment by Lucete28** [comment]
# [Genius](https://rapidapi.com/Glavier/api/genius-song-lyrics1)

**Comment by bksooon** [comment]
# [TheAudioDB](https://www.theaudiodb.com/)

**Comment by mews2000** [comment]
Itunes Search API

**Comment by bksooon** [comment]
# [last.fm](https://www.last.fm/api/intro)

## [DOCS](https://www.last.fm/api)

 - 유료인지 무료인지 확인중

## 형식
API Methods
album
[album.addTags](https://www.last.fm/api/show/album.addTags)
[album.getInfo](https://www.last.fm/api/show/album.getInfo)
[album.getTags](https://www.last.fm/api/show/album.getTags)
[album.getTopTags](https://www.last.fm/api/show/album.getTopTags)
[album.removeTag](https://www.last.fm/api/show/album.removeTag)
[album.search](https://www.last.fm/api/show/album.search)
artist
[artist.addTags](https://www.last.fm/api/show/artist.addTags)
[artist.getCorrection](https://www.last.fm/api/show/artist.getCorrection)
[artist.getInfo](https://www.last.fm/api/show/artist.getInfo)
[artist.getSimilar](https://www.last.fm/api/show/artist.getSimilar)
[artist.getTags](https://www.last.fm/api/show/artist.getTags)
[artist.getTopAlbums](https://www.last.fm/api/show/artist.getTopAlbums)
[artist.getTopTags](https://www.last.fm/api/show/artist.getTopTags)
[artist.getTopTracks](https://www.last.fm/api/show/artist.getTopTracks)
[artist.removeTag](https://www.last.fm/api/show/artist.removeTag)
[artist.search](https://www.last.fm/api/show/artist.search)
auth
[auth.getMobileSession](https://www.last.fm/api/show/auth.getMobileSession)
[auth.getSession](https://www.last.fm/api/show/auth.getSession)
[auth.getToken](https://www.last.fm/api/show/auth.getToken)
chart
[chart.getTopArtists](https://www.last.fm/api/show/chart.getTopArtists)
[chart.getTopTags](https://www.last.fm/api/show/chart.getTopTags)
[chart.getTopTracks](https://www.last.fm/api/show/chart.getTopTracks)
geo
[geo.getTopArtists](https://www.last.fm/api/show/geo.getTopArtists)
[geo.getTopTracks](https://www.last.fm/api/show/geo.getTopTracks)
library
[library.getArtists](https://www.last.fm/api/show/library.getArtists)
tag
[tag.getInfo](https://www.last.fm/api/show/tag.getInfo)
[tag.getSimilar](https://www.last.fm/api/show/tag.getSimilar)
[tag.getTopAlbums](https://www.last.fm/api/show/tag.getTopAlbums)
[tag.getTopArtists](https://www.last.fm/api/show/tag.getTopArtists)
[tag.getTopTags](https://www.last.fm/api/show/tag.getTopTags)
[tag.getTopTracks](https://www.last.fm/api/show/tag.getTopTracks)
[tag.getWeeklyChartList](https://www.last.fm/api/show/tag.getWeeklyChartList)
track
[track.addTags](https://www.last.fm/api/show/track.addTags)
[track.getCorrection](https://www.last.fm/api/show/track.getCorrection)
[track.getInfo](https://www.last.fm/api/show/track.getInfo)
[track.getSimilar](https://www.last.fm/api/show/track.getSimilar)
[track.getTags](https://www.last.fm/api/show/track.getTags)
[track.getTopTags](https://www.last.fm/api/show/track.getTopTags)
[track.love](https://www.last.fm/api/show/track.love)
[track.removeTag](https://www.last.fm/api/show/track.removeTag)
[track.scrobble](https://www.last.fm/api/show/track.scrobble)
[track.search](https://www.last.fm/api/show/track.search)
[track.unlove](https://www.last.fm/api/show/track.unlove)
[track.updateNowPlaying](https://www.last.fm/api/show/track.updateNowPlaying)
user
[user.getFriends](https://www.last.fm/api/show/user.getFriends)
[user.getInfo](https://www.last.fm/api/show/user.getInfo)
[user.getLovedTracks](https://www.last.fm/api/show/user.getLovedTracks)
[user.getPersonalTags](https://www.last.fm/api/show/user.getPersonalTags)
[user.getRecentTracks](https://www.last.fm/api/show/user.getRecentTracks)
[user.getTopAlbums](https://www.last.fm/api/show/user.getTopAlbums)
[user.getTopArtists](https://www.last.fm/api/show/user.getTopArtists)
[user.getTopTags](https://www.last.fm/api/show/user.getTopTags)
[user.getTopTracks](https://www.last.fm/api/show/user.getTopTracks)
[user.getWeeklyAlbumChart](https://www.last.fm/api/show/user.getWeeklyAlbumChart)
[user.getWeeklyArtistChart](https://www.last.fm/api/show/user.getWeeklyArtistChart)
[user.getWeeklyChartList](https://www.last.fm/api/show/user.getWeeklyChartList)
[user.getWeeklyTrackChart](https://www.last.fm/api/show/user.getWeeklyTrackChart)

**Comment by json9101** [comment]
Shazam
shazam-events/list
search
auto-complete
songs/v2/get-details

**Comment by jungssg** [comment]
# musixmatch 
(가사 특화, 무료버전 매일2000회 요청, 유료는 가격확인중)

https://developer.musixmatch.com/documentation/api-methods
<img width="206" alt="스크린샷 2023-08-21 오전 11 52 47" src="https://github.com/Melon-Shake/main_melonshake/assets/131239981/3a5a5c6e-4ed1-48be-97bd-bad663694dab">

**Comment by json9101** [comment]
# Deezer
Infos
Radio
Genre
* Search
Playlist
Artist
Editorial
Track
Comment
Album

**Comment by iamyanghee** [comment]
### api 토의에서 덧붙이는 말들

- 트랙이 api A 에는 있는데 B 에는 없을 수 있다
- 그리고 있더라도 검색 결과가 정확하지 않을 수 있다
- 콜 제한 해소(안) : 서비스 후원해주세요
- 콜 제한 해소(안) : 각 사용자별로 개발자 계정/토큰 발급받게 한다
- 콜 제한 해소(안) : 선적재 말고 후적재 
- 검색결과를 all / a / b / c 태그로 나눠서 보여줄 수 있지 않나
- 파일 떨어지는 건 rename 하면 되고
- shazam 기준 재생수 받을 수 있다 
  - 우리 서비스만의 랭킹을 할 떄, shazam 에서는 재생수 기준, spotify 는 팔로워수 기준 등으로 기준 
-
