### ISSUE TITLE
[컴퓨터 속 귀신] 데이터가 NoneType 이었지만 아니었던 건에 대하여

### ISSUE THREAD

**Issue by Lucete28** [Melon-Shake/API#125]
## 개요
- NoneType 데이터를 리스트로 반환 받았는데 set 했더니 내용이 생겼다.

## 상세 내용
- 쿼리문
![image](https://github.com/Melon-Shake/API/assets/97825872/d1f3a431-35c1-4a0f-a121-3baa784b4b39)
- 나온 결과 
![image](https://github.com/Melon-Shake/API/assets/97825872/586b58f9-9c67-4fe2-91a5-bfaecfa1933e)
- 상세 
![image](https://github.com/Melon-Shake/API/assets/97825872/c54a8cd9-e142-4642-a854-7404e38eda95)
- set()
![image](https://github.com/Melon-Shake/API/assets/97825872/5565c377-4a00-43dc-b685-93c85a4beae6)

**Comment by bksooon** [comment]
![LGTM](https://i.lgtm.fun/2ksw.png)
