### ISSUE TITLE
팀 멜론 쉐이크 갤러리

### ISSUE THREAD

**Issue by Lucete28** [Melon-Shake/API#15]
손병규 | 이양희 | 박기범
--|--|--
![KakaoTalk_20230824_103727631_05](https://github.com/Melon-Shake/main_melonshake/assets/97825872/3d0b270b-ba2b-4ccc-8eb8-b8bec566ffb6)|![KakaoTalk_20230824_103727631](https://github.com/Melon-Shake/main_melonshake/assets/97825872/2f568d66-c832-4f58-bd2f-2e486ebc769a)|![KakaoTalk_20230824_103727631_04](https://github.com/Melon-Shake/main_melonshake/assets/97825872/3c7b05f9-1779-4d86-8873-ea6230f47592)|
 | 한정석 | 손준성 | 정호연
![KakaoTalk_20230824_103727631_01](https://github.com/Melon-Shake/main_melonshake/assets/97825872/fdc9b215-5152-48bc-aa19-bcd44097aebb)|![KakaoTalk_20230824_103727631_02](https://github.com/Melon-Shake/main_melonshake/assets/97825872/57298fe7-c65d-4db3-85cd-d822e9b5018d)|![KakaoTalk_20230627_154647825](https://github.com/Melon-Shake/API/assets/79441624/6693b425-8b88-44fb-982e-f8ea52f433c0)

**Comment by Lucete28** [comment]
## 2023 - 08 - 18
### PD24 Final Project 시작 !
![KakaoTalk_20230818_101551512_02](https://github.com/Melon-Shake/main_melonshake/assets/97825872/078bbafc-d68f-4a20-96a8-0bd4b1d24237)

**Comment by Lucete28** [comment]
## 2023 - 08 -22
### 첫 칸반 
![20230822_칸반](https://github.com/Melon-Shake/main_melonshake/assets/97825872/05f8c007-7800-487b-b896-ab9a0c16ef8e)

**Comment by Lucete28** [comment]
## 2023 - 08 - 23
### 김모세 네이버 글로벌 애자일 코치님과 함께 칸
![20230823_애자일 코치님 칸반](https://github.com/Melon-Shake/main_melonshake/assets/97825872/6604ab74-2694-432e-a270-a092061a3ab8)

### 데이터 테이블 통합 회의
![20230823_데이터 테이블 회의](https://github.com/Melon-Shake/main_melonshake/assets/97825872/7e0b1440-1e4b-4f7d-b71f-b05d0cdd1c72)

**Comment by Lucete28** [comment]
## 2023 - 08 - 29
### 박일호 멘토님과 첫 회의
![화면 캡처 2023-08-29 200518](https://github.com/Melon-Shake/main_melonshake/assets/97825872/48c196c9-cd00-47c3-aca1-69d34b7f0a94)

**Comment by Lucete28** [comment]
## 2023 - 08 - 30 
### 강사님과 다정하게 한컷!
![화면 캡처 2023-08-30 175558](https://github.com/Melon-Shake/main_melonshake/assets/97825872/795ee70e-e8b4-4d9a-b806-d1793ffe2895)

**Comment by bksooon** [comment]
![image](https://github.com/Melon-Shake/main_melonshake/assets/79441624/0e945c61-2548-4b7c-8af8-b0e189f1ee51)
<br>
![image](https://github.com/Melon-Shake/main_melonshake/assets/79441624/fbd36a4c-a646-4e56-b670-135abeba5ba8)

**Comment by Lucete28** [comment]
## 2023 - 09 - 11
### 활발한 Kanban!
![image](https://github.com/Melon-Shake/API/assets/97825872/352e95e1-191e-45e3-87d8-30f8e561ba93)
