### ISSUE TITLE
Genius Api 

### ISSUE THREAD

**Issue by Lucete28** [Melon-Shake/API#16]
Genius API의 모든 것

**Comment by Lucete28** [comment]
- [ ] 문제 : 무료 앱이라 하여도 genius의 허가가 필요할 수 있음
    - [ ] [관련 질문](https://genius.com/discussions/420892-Using-genius-api-for-a-free-ios-app-musichub)
    - [ ] 문의중

**Comment by jungssg** [comment]
genius가 답이다
