### ISSUE TITLE
각자 담당한 기능을 기반으로 팀 칸반을 처음 진행함

### ISSUE THREAD

**Issue by iamyanghee** [Melon-Shake/API#2]
### 계획한 일정
- 09:20 ~ 09:50 아침 토의 
- 10:00 ~ 15:00 각자 담당한 기능 정리 정갈하게~
- 15:00 ~ 18:00 db, 파이프라인, 개발공통환경 맞추기

### 진행한 일정
- 09:20 ~ 09:50 아침 토의 
- 10:00 ~14:30 각자 담당한 기능 구상
- 14:30 ~ 15:30 칸반 후 멘토 결정 토의
-

**Comment by iamyanghee** [comment]
## 오늘 진행한 칸반
![20230822_152214](https://github.com/Melon-Shake/main_melonshake/assets/131243101/bc729be9-f01b-4e0b-8cbe-58852159535b)

**Comment by iamyanghee** [comment]
## README 정비

**Comment by jungssg** [comment]
Melon-shake : 음원정보 종합서비스

**Comment by Lucete28** [comment]
사용자 성향 분석 , 옵션 설정을 통한 플리생성

**Comment by iamyanghee** [comment]
## 드디어 DB !
