### ISSUE TITLE
AWS RDS 연결 관련 issue

### ISSUE THREAD

**Issue by mews2000** [Melon-Shake/API#25]
현재 AWS RDS로 생성힌 DB에 연결이 안되는 문제가 있습니다.
<br/>
<br/>
![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/84c5332f-0566-43d6-81f9-59b712c64dca)

발생한 에러 메세지는 연결 시도 시간 초과입니다.
<br/>
<br/>
<br/>
우선 AWS에서 설명하는 RDS 연결 문제 해결 방법은 다음과 같습니다.
<br/>
![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/96abfb17-69d7-44aa-b2dc-043988daccfc)
![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/af8971ee-afbb-43c2-9e09-032ed48cd63e)
<br/>
<br/>
<br/>
<br/>

![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/f9dc766f-4900-4411-abd2-76906dadd07d)
DB 인스턴스 사용가능 상태는 확인했습니다.
<br/>
<br/>
<br/>
<br/>
![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/7b9fa77a-9c7d-4c2d-88a0-8dee6335b396)
![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/5ac4488d-8996-499d-b83b-a472805b643a)

<br/>
<br>
<br>

![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/da196c8d-74ca-483e-9c5f-e6832a1ceced)

<br>
<br>
우선 위와 같이 엔드포인트와 포트, 데이터베이스 이름, 유저 이름, 비밀번호는 여러번 검증했습니다.
DB 인스턴스의 Public Access도 허용했습니다.
postgres 버전 15.3 역시 연결하려는 툴인 dbeaver에서 문제없이 돌아가는 것을 확인했습니다.
<br/><br/><br/><br/>
이외에 확인 가능한 문제로는 보안그룹의 인바운드 규칙 설정, 네트워크 ACL 인바운드 규칙, 라우팅 테이블의 라우팅 대상입니다.
<br>

![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/ce85607e-1e1e-45f8-a61f-afa9709e145e)

<br><br> 위와 같이 내IP를 규칙에 집어 넣었습니다.<br><br>
네트워크 ACL 인바운드 규칙은 아래와 같았습니다.<br>

![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/fd1183a1-8219-4e55-9a49-f330a8fb11fd)

<br>0.0.0.0/0 허용이 있어 문제가 되지 않을 것으로 보입니다.

라우팅 테이블의 라우팅 대상은 아래와 같았습니다.<br>

![image](https://github.com/Melon-Shake/main_melonshake/assets/51077803/103fdb29-25df-4cf9-90fd-41fe16300e71)

<br>이 역시 0.0.0.0/0 테이블이 있어 문제가 되지 않을 것으로 보입니다.
<br>무엇이 문제일까요?

**Comment by mews2000** [comment]
생성한지 오래된 계정의 경우 VPC 정보 등에 문제가 생길 수 있다고 합니다.
VPC나 보안그룹 등 데이터베이스 생성시 사용되는 원래 있던 정보들을 전부 삭제하고 다시 만들면 제대로 될 가능성이 있다고 합니다.

현재 이슈는 원래 지역이던 서울을 도쿄로 바꾼 뒤 다시 DB 인스턴스를 생성했을때 잘 연결되는 것을 확인했습니다.

**Comment by bksooon** [comment]
![LGTM](https://i.lgtm.fun/2jze.png)
