### ISSUE TITLE
[업무규약] 이슈 템플릿 작성 예시

### ISSUE THREAD

**Issue by iamyanghee** [Melon-Shake/API#37]
## 개요
- 이슈 작성 시 모두가 파악하기 용이한 형태로 통일하기 위해 최소한의 양식입니다.
- 병규 님 작성하신 이슈 템플릿에 대해 피드백 드리기 위해 예시 작성하였습니다.

## 상세 내용
- 제목은 `[키워드] 한줄 요약` 의 형태로 작성해주세요.
- 이후 내용은 크게 3단 `세줄요약` `상세내용` `작업사항` 으로 구성하되, 소제목명과 크기는 자유롭게 진행해주세요.
  - `세줄요약` 은 해당 이슈가 어떤 이슈인지, 아래 내용이 어떻게 서술될 것인지 예상할 수 있도록 적어주세요.
  - `상세내용` 은 어떤 배경이고, 그래서 어떤 조치 등을 진행했고, 그럼에도 어떤 상황인지 등 알려주세요.
  - `작업사항` 은 todo 형태로 작성해주시고, 본인의 작업순서 또는 다른 팀원에게 협조 요청할 사항에 대해 적어주세요.
    - 이후 하나씩 체크하면서 아래로 코멘트 셀을 추가하시길 권유드립니다.

## 진행할 작업사항
- [x] 병규 님에게 해당 템플릿 전달
- [x] 다른 팀원들에게 의견 확인?

**Comment by bksooon** [comment]
![LGTM](https://i.lgtm.fun/2jzo.gif)
