### ISSUE TITLE
[ Fast API ] 정호연이 에러를 빨리 확인 하는법

### ISSUE THREAD

**Issue by Lucete28** [Melon-Shake/API#46]
## 개요
- api가 서버에서 실행될 때 코드가 복잡할 수록 문제가 있는지 확인하기 어렵습니다.
- 우리가 로그?를 잘 남겨놔야 빨리 처리 할 수 있지요
- 여기 이슈는 정호연이 그동안 에러 위치(원인)를 확인하기 위해 사용한 방법입니다.

### (1단계) 기본적으로 fastapi에서 처리 
아래 코드에서 보이는것처럼 HTTPException을 통해 Fast api 자체의 오류인지 확인합니다.
```py
from fastapi import FastAPI,HTTPException

@app.post("/lyric_input/")
def lyric_input(item : lyric_data):
    artist = item.artist
    result = lyric_search_and_input(artist)

    if result:
        return {"result" : f"Lyrics have been added to track_id : {track_id}"}
    else:
        raise HTTPException(status_code=404, detail="Lyric ERR.")
```

### (2단계) result 딕셔너리 리턴 활용
1. 코드(함수) 가 시작할때 빈 result 딕셔너리를 선언 
2. if 문, try/exept문 for문 등 작업이 이루어 질 때마다 딕셔너리에 result['작업']=결과 형식으로 계속 추가
3. 마지막에 result를 return시켜줍니다.
```py
def tmp( ):
    result = { }
    if True:
        something_result = do_something()
        result['do_something'] = something_result 
    else:
        nothing_result = do_nothing()
        result['do_nothing'] = nothing_result
    return result
```

**Comment by jungssg** [comment]
![LGTM](https://i.lgtm.fun/2k3x.gif)
