### ISSUE TITLE
통합검색 기능 고민

### ISSUE THREAD

**Issue by bksooon** [Melon-Shake/API#7]

**Comment by iamyanghee** [comment]
## 검색 플로우

- 키워드를 검색창에 입력 (예: 아이유)
- 해당 키워드를 **`spotify web api`** 호출 -> 앨범, 가수, 곡 3가지 결과가 나와야함

  - search -> id
    - type : album, artist, track 

  - 키워드가 artist 라면
    - 가수 `https://api.spotify.com/v1/artists/{id}`
    - 곡 `https://api.spotify.com/v1/artists/{id}/top-tracks`
    - 앨범 `https://api.spotify.com/v1/artists/{id}/albums`

  - 키워드가 album 라면
    - 곡 `https://api.spotify.com/v1/albums/{id}/tracks`
    - 앨범 `https://api.spotify.com/v1/albums/{id}`
    - 가수는 앨범으로 던져서 받은 json 파싱해서 -> `https://api.spotify.com/v1/artists/{id}`

  - 키워드가 track 라면
    - 곡 `https://api.spotify.com/v1/tracks/{id}`
    - 가수는 곡으로 던져서 받은 json 파싱해서 -> `https://api.spotify.com/v1/artists/{id}` `https://api.spotify.com/v1/artists/{id}/albums`

- 검색한 키워드와 응답 json 을 저장할 것인가?
- artist, track, album - 3개의 덩어리를 파싱해서 각 레이아웃으로 출력


![Image](https://user-images.githubusercontent.com/131243101/262213512-7c53dd21-6290-4580-b2c3-0c0c17393f3b.png)
![Image](https://user-images.githubusercontent.com/131243101/262213513-163baf4c-2a0f-407c-8e32-65db5e589423.png)
![Image](https://user-images.githubusercontent.com/131243101/262213511-aeefeaa7-f26e-4fab-91a3-9cf60596f3de.png)
